[package]
name = "valor_core"
description = "Virto Async Light Open Runtime"
license = "GPL-3.0-or-later"
version = "0.6.0"
authors = ["Daniel Olano <daniel@olanod.com>", "Johan Alexis Duque Cadena <johan.duque@gmail.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
embassy-executor = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = ["log", "std", "nightly", "integrated-timers"] }
embassy-time = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = ["log", "std", "nightly"] }
embedded-io = { version = "0.4.0", features = ["async", "std"] }
env_logger = "0.10.0"
log = "0.4.17"
wasm_runtime = { path = "./wasm" }

[features]

[workspace]
members = [
	"wasm",
]
[profile.release.package.valor_web]
opt-level = "s"

[profile.release]
lto = true
strip = true
# opt-level = 3

[profile.dev]
opt-level = 0

