[package]
name = "valor_core"
description = "Plugin runtime as HTTP API running in server and browser"
license = "GPL-3.0-or-later"
version = "0.5.0-beta.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
async-trait = "0.1.49"
http-types = "2.11.0"
path-tree = "0.1.12"
hashbrown = "0.11.2"
serde = { version = "1.0.125", default-features = false, features = ["alloc", "derive"], optional = true }
serde_json = { version = "1.0.64", default-features = false, features = ["alloc"] }
valor_plugin = { version = "0.5.0-beta.0", path = "./valor_plugin", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
http-client = { version = "6.3.5", optional = true, features = ["h1_client"] }

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
mockito = "0.30.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.73", optional = true }
js-sys = { version = "0.3.50", optional = true }
wasm-bindgen-futures = { version = "0.4.23", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
http-client = { version = "6.3.5", optional = true, features = ["wasm_client"] }

[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3.50"
optional = true
features = ["RequestInit", "Request", "ResponseInit", "Response", "Headers"]

[target.'cfg(target_arch="wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.23"

[features]
std = []
_serde_ = ["serde"]
util = ["valor_plugin"]
native = ["_serde_", "std"]
web = [
	"util",
	"wasm-bindgen", 
	"wasm-bindgen-futures", 
	"js-sys",
	"web-sys",
	"wee_alloc",
]
proxy = ["http-client"]

[workspace]
default-members = ["valor_bin"]
members = [
	"valor_bin",
	"valor_web",
	"valor_plugin",

	"examples/hello_plugin",
	"examples/with_state",
]

[profile.release.package.valor_web]
opt-level = "s"

[profile.release]
lto = true
