[package]
name = "valor_core"
description = "Plugin runtime as HTTP API running in server and browser"
license = "GPL-3.0-or-later"
version = "0.5.2-beta.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
async-trait = "0.1.52"
http-types = { git = "https://github.com/http-rs/http-types.git", branch = "main", default-features = false, features = ["serde"] }
path-tree = { version = "0.2.2", optional = true }
hashbrown = "0.11.2"
serde = { version = "1.0.131", default-features = false, features = ["alloc", "derive"], optional = true }
serde_json = { version = "1.0.73", default-features = false, features = ["alloc"] }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
http-client = { version = "6.5.1", optional = true, features = ["h1_client"] }

[dev-dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
mockito = "0.30.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.78", optional = true }
js-sys = { version = "0.3.55", optional = true }
wasm-bindgen-futures = { version = "0.4.28", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
http-client = { version = "6.5.1", optional = true, features = ["wasm_client"] }

[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3.55"
optional = true
features = ["RequestInit", "Request", "ResponseInit", "Response", "Headers"]

[target.'cfg(target_arch="wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.28"

[features]
std = []
runtime = ["path-tree"]
util = []
native = ["runtime", "serde", "std"]
web = [
	"runtime",
	"util",
	"wasm-bindgen", 
	"wasm-bindgen-futures", 
	"js-sys",
	"web-sys",
	"wee_alloc",
]
proxy = ["http-client"]

[workspace]
default-members = ["native"]
members = [
	"native",
	"web",
	"embedded",
	"wasm",

	"examples/hello_service",
]

[profile.release.package.valor_web]
opt-level = "s"

[profile.release]
lto = true
strip = true
