[package]
name = "valor_plugin_build"
version = "0.5.1-beta.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.69", default-features = false, features = ["full", "parsing"] }

